import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '@/shared/components/shared/header';

const cyrillicOld = localFont({
  src: '../public/fonts/CyrillicOld.woff2',
  variable: '--font-cyrillic-old',
});

export const metadata: Metadata = {
  title: 'УстА',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cyrillicOld.variable} antialiased px-3 lg:px-4 xl:px-0`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
