import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from '@/shared/components/ui/sonner';

const cyrillicOld = localFont({
  src: '../public/fonts/CyrillicOld.woff2',
  variable: '--font-cyrillic-old',
});

export const metadata: Metadata = {
  title: 'УстА',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cyrillicOld.variable} antialiased `}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
